### ISSUE TITLE
Resources deleted on pod restart

### ISSUE THREAD

**Issue by mo-hit** [tryretool/retool-onpremise#79] opened 2021-10-12 23:53 UTC
Hello,
I've setup retool on-premise in a Kubernetes cluster. I've setup an external postgres in RDS. Currently there is a single replica. However, if I go to restart the pod, I notice that all my resources (DBs, S3) are no longer there on restart. Looking at the logs of the container, I can see that it connects to my DB instance and I can see active connections on the DB. Users are preserved upon restarts, it's just resources that are not saved. Is this correct functionality?

**Comment by christopher-wong** [comment] 2022-04-21 19:43
Hi @julieechenn is there any update to this? We're still seeing resources being deleted and permissions issues after pods restart (when pointing to an external RDS instance).

**Comment by christopher-wong** [comment] 2022-04-27 00:47
I closed a duplicate issue that I opened which appears to be a dupe of this one. https://github.com/tryretool/retool-onpremise/issues/94

**Comment by christopher-wong** [comment] 2022-04-28 21:32
After talking to Retool support we believe we've discovered root cause on this issue. If you are deploying via the Helm charts, set an explicit encryption key on initial install. This resolved the issue of resources not surviving pod restarts or page refreshes.

Set the value here: https://github.com/tryretool/retool-helm/blob/main/values.yaml#L20

**Comment by bdjohnson529** [comment] 2023-05-09 23:47
Hi @christopher-wong  - sounds like you were able to get this issue resolved. I'm closing this issue - please feel free to reach out to **support@retool.com** with any questions or concerns.

**Closed by bdjohnson529** 2023-05-09 23:47 UTC
